xmac94x/GitHub actions
amethyst/specs pull request #749
Opened 2022-06-21 17:57 UTC by xMAC94x

Pure CI change, just get rid of travis and go to actions (i hope this works)

2022-06-21 18:45 UTC, AngelOnFira commented
Was most of this CI code taken from another Amethyst repo? It looks like it was. Would be curious to see how their CI runs. Also, I feel like there's a way to get CI to run on a fork? I'll try to run this branch on mine and we can see how it does.

2022-06-21 18:51 UTC, AngelOnFira commented
I have CI running on my fork, we can check that the changes run there :)

https://github.com/AngelOnFira/specs/pull/1

2022-06-21 20:26 UTC, AngelOnFira requested changes
Just a few things :)

2022-06-21 20:26 UTC, AngelOnFira commented on .github/workflows/ci.yml
> +      #  if: matrix.toolchain == 'stable' && matrix.os == 'ubuntu-latest'
Maybe remove sections that are commented out?

2022-06-21 20:26 UTC, AngelOnFira commented on deny.toml
> +allow = ["MIT", "Apache-2.0", "Unlicense", "BSD-3-Clause"]
Does this align with the license on this repo?

2022-06-21 20:35 UTC, AngelOnFira commented on bors.toml
> +]
afaik the Rust org uses Bors to queue tests on PRs: https://bors.tech/

I checked out several merged PRs on the Legion repo, and none seem to be using Bors. Can we remove this file?

2022-06-21 20:38 UTC, AngelOnFira commented on deny.toml
> +allow = ["MIT", "Apache-2.0", "Unlicense", "BSD-3-Clause"]
Actually I guess adding Apache 2 as a dual licence wouldn't restrict which would be allow, so that should be fine :+1:

2022-06-21 20:41 UTC, AngelOnFira approved these changes

2022-06-21 20:45 UTC, AngelOnFira commented
@fhaynes looks like I'll need your perms to make some changes to this repo. We'll need to remove the required status on the `continuous-integration/travis-ci ` job, and potentially add the requirement to some new jobs after this merges.

2022-06-22 02:45 UTC, merged

2022-06-22 02:53 UTC, fhaynes commented
@AngelOnFira @xMAC94x I merged this, and sent you an invite to our long-disused gitter. Please drop by if you have a minute, I'd like to know what the goal here is.